ALTER TABLE cves ADD COLUMN IF NOT EXISTS cwe_id VARCHAR(50) DEFAULT '';
ALTER TABLE cves ADD COLUMN IF NOT EXISTS references TEXT DEFAULT '';
ALTER TABLE cves ADD COLUMN IF NOT EXISTS affected_products TEXT DEFAULT '';
ALTER TABLE cves ADD COLUMN IF NOT EXISTS source VARCHAR(50) DEFAULT 'manual';
