scrape_configs:
  - job_name: 'patchmaster'
    metrics_path: /metrics
    scrape_interval: 30s
    static_configs:
      - targets:
          - PATCHMASTER_IP:8000

  - job_name: 'patchmaster-agents'
    metrics_path: /metrics
    scrape_interval: 30s
    static_configs:
      - targets:
          - AGENT1_IP:9100
          - AGENT2_IP:9100
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: "(.*):9100"
        replacement: "$1"
