[pytest]
filterwarnings =
    ignore:'crypt' is deprecated.*:DeprecationWarning:passlib.utils
    ignore:Module already imported so cannot be rewritten; anyio:pytest.PytestAssertRewriteWarning
    ignore:The executor did not finishing joining its threads within 300 seconds\.:RuntimeWarning:asyncio.events
